### ISSUE TITLE
Implement async mutex datastructure variants

### ISSUE THREAD

**Issue by theli-ua** [kanidm/concread#38]
Currently guard will use parking_lot's GuardNoSend

**Comment by Firstyear** [comment]
I'll have to think about this. I think there is no reason it can't be send today, but I'm curious what you are trying to achieve. Why not send/clone the BptreeMap itself and start the write txn at the destination? I'd also want to be sure that the ref to caller can be guaranteed to live long enough over a send too. 

I'm just starting a rewrite of the tree internals right now to improve garbage collection, so that could impact this too.

**Comment by theli-ua** [comment]
Just to be able to use across async points.

**Comment by Firstyear** [comment]
Ahhhhhhh that makes much more sense now. Okay, what would be the needed changes do you think to make this capable of being Send?

**Comment by Firstyear** [comment]
Okay, it looks like both https://doc.rust-lang.org/std/sync/struct.MutexGuard.html and https://amanieu.github.io/parking_lot/parking_lot/struct.MutexGuard.html are not Send, so there must be a reason for this. I would say understanding that is probably key to being able to make the writetxn send.

**Comment by Firstyear** [comment]
Okay, I was reflecting on this overnight, and I think beyond the !Send issue, you'd have other issues with async anyway. Because of the nature of async, you have many tasks interleaving, and many of those could be write tasks. That's why tokio has special mutex types to handle this situation to prevent deadlocking between resources:

https://docs.rs/tokio/0.2.21/tokio/sync/struct.Mutex.html

The mutex guard here *is* Send and is able to be used with async, so I think that if you wanted to be able to use the BptreeMap, there would need to be a parallel version which uses this lock instead. Async is a bit like "taint", where it go through everything it touches. You can't use the async mutex in a non-async stack, and vice versa you can't use the non-async lock in an async stack.

So to resolve this, I think the path would be:

* Create a parallel top-level bptree map.rs that changes parking lot to tokio mutex, and change any other required top level functions to be async
* Write an async test suite to check it functions as expected, especially with multiple writers staying consistent.

The tree internals could remain the same, because they are all generally implemented with unsafe and assume you are behind the lock, all of the thread safety and memory ordering comes from the top level locking/map operations. So the scope to change to make this async capable would be low.

If you are interested, I'd love to review any commits on contributions, and to help answer any questions you have, or I'll probably do this later once my current tree internals rewrite is complete (I don't really have a need for async at this low level so it's not a high priority for me, but I will add it eventually because it's useful to others).

Hope that helps,

**Comment by theli-ua** [comment]
Right, though instead of using tokio's mutex you could still use parking lot but use reentrant mutex. usual mutex is not send because if you try to lock it from the same thread again you'll deadlock. Reentrant mutex allows that and thus is Send

**Comment by Firstyear** [comment]
I'd be pretty nervous about just assuming that reentrant mutex would "just work" in async, which is why I think tokio's is better to reach for here.

**Comment by theli-ua** [comment]
I mean, basically what I was asking for is just a Send variant of Txn handles :)

**Comment by Firstyear** [comment]
For sure! I just want to be sure that whatever is done is correct :) Having support to use txn handles in async would be great, but I think most of the complexity is with write txns of course. So I think for now, my plan is still tokio mutex, but I'll read up on the parking lot reentrant one to be sure of what I think in my head is the case. :)

**Comment by Firstyear** [comment]
Right, so I did some reading and there is a key difference: 

> /// This type acts similarly to an asynchronous [`std::sync::Mutex`], with one
> /// major difference: [`lock`] does not block. Another difference is that the
> /// lock guard can be held across await points.

Reentrant doesn't provide these guarantees, which means that while it may be Send, it *could* cause a deadlocking scenario in async, because you could have:

```
async task 1      async task 2

lock wr txn
start IO
yield
                  attempt to lock wr txn
                  *DEADLOCK*
```

Tokio's mutex in async task 2 on the attempt to lock would immediately fail and yield, allowing task 1 to continue IO to completion, which would then allow the wrtxn to be dropped, and then async task 2 could continue. The re-entrant mutex would not prevent this case, which could cause async task deadlocking.

As a result of this, I think my summary is:

* Yes, async support in concread would be awesome
* We need to use the tokio mutex type in place of parking_lot mutex for it
* We need a way to genericise the tree based on the type of mutex guard in use

Hope that helps,

**Comment by Firstyear** [comment]
Actually, worse, if you used re-entrant in this case, the async task 2 would see an incomplete/partial TXN from async task 1 in progress, which could corrupt the tree/garbage states. So we really *can't* use reentrant here.

**Comment by theli-ua** [comment]
You could just just use  send_guard parking_lot's feature for now. While that could technically deadlock (and it probably will in single threaded executor) it gives you Send, you could expose that as send_guard feature

**Comment by Firstyear** [comment]
I'd rather not because it can deadlock. I'd rather do it right for async/await, than do something that's not going to work.

Recently I've been thinking I'll need this functionality anyway, so it will happen :)

**Comment by Firstyear** [comment]
https://github.com/kanidm/concread/pull/41
