### ISSUE TITLE
Undefined Behavior in ARCacheReadTxn::get

### ISSUE THREAD

**Issue by y21** [kanidm/concread#78]
https://github.com/kanidm/concread/blob/020e8c2ad2fba94cd5efff759fdae20c332742d1/src/arcache/mod.rs#L2041-L2043

The transmute is UB according to miri, the language reference and the [Rustonomicon](https://doc.rust-lang.org/nomicon/transmutes.html):
> Transmuting an `&` to `&mut` is Undefined Behavior. While certain usages may *appear* safe, note that the Rust optimizer is free to assume that a shared reference won't change through its lifetime and thus such transmutation will run afoul of those assumptions. So:
> - Transmuting an & to &mut is always Undefined Behavior.

<details>
<summary>Miri output</summary>

```
Undefined Behavior: trying to reborrow <914429> for Unique permission at alloc355143[0x0], but that tag only grants SharedReadOnly permission for this location
    --> src/arcache/mod.rs:2061:36
     |
2061 |                         let hits = std::mem::transmute::<&u32, &mut u32>(&self.hits);
     |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |                                    |
     |                                    trying to reborrow <914429> for Unique permission at alloc355143[0x0], but that tag only grants SharedReadOnly permission for this location
     |                                    this error occurs as part of a reborrow at alloc355143[0x0..0x4]
```
</details>

Thought I'd let you know as the README says: 
> This library has extensive testing, and passes it's test suite under [miri](https://github.com/rust-lang/miri), a rust undefined behaviour checker. If you find an issue however, please let us know so we can fix it!

**Comment by Firstyear** [comment]
Thanks! Yeah, this miri rule looks new - we need to also update to use sptr to allow pointer tracking given the amount of raw pointer handling we do.

In this situation, this *is* safe, because we are mutating a value from within the mut of self, so we are the only holder, the reason we need that undefined transmute is because the rust borrow checker is too coarse. When we borrow for the call to .get() it makes the whole instance of self immutable as a borrow meaning we also can't mutate the internal set of counters. We could refactor a bit to get around this though and to "appease the powers that be".

**Comment by Firstyear** [comment]
It's all good. I think in this case I mean it's safe WRT to thread safety, but it's UB by Rust's ideals. I'm going to clean it up and fix it anyway, since appeasing miri is worth it :)
